# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobuf import auth_pb2 as protobuf_dot_auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthenticateUser = channel.unary_unary(
                '/todo_auth.AuthService/AuthenticateUser',
                request_serializer=protobuf_dot_auth__pb2.Token.SerializeToString,
                response_deserializer=protobuf_dot_auth__pb2.UserProfile.FromString,
                )
        self.RegisterUser = channel.unary_unary(
                '/todo_auth.AuthService/RegisterUser',
                request_serializer=protobuf_dot_auth__pb2.UserRegistrationForm.SerializeToString,
                response_deserializer=protobuf_dot_auth__pb2.Token.FromString,
                )
        self.LoginUser = channel.unary_unary(
                '/todo_auth.AuthService/LoginUser',
                request_serializer=protobuf_dot_auth__pb2.UserCredentials.SerializeToString,
                response_deserializer=protobuf_dot_auth__pb2.Token.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthenticateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthenticateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateUser,
                    request_deserializer=protobuf_dot_auth__pb2.Token.FromString,
                    response_serializer=protobuf_dot_auth__pb2.UserProfile.SerializeToString,
            ),
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=protobuf_dot_auth__pb2.UserRegistrationForm.FromString,
                    response_serializer=protobuf_dot_auth__pb2.Token.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=protobuf_dot_auth__pb2.UserCredentials.FromString,
                    response_serializer=protobuf_dot_auth__pb2.Token.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todo_auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthenticateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo_auth.AuthService/AuthenticateUser',
            protobuf_dot_auth__pb2.Token.SerializeToString,
            protobuf_dot_auth__pb2.UserProfile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo_auth.AuthService/RegisterUser',
            protobuf_dot_auth__pb2.UserRegistrationForm.SerializeToString,
            protobuf_dot_auth__pb2.Token.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/todo_auth.AuthService/LoginUser',
            protobuf_dot_auth__pb2.UserCredentials.SerializeToString,
            protobuf_dot_auth__pb2.Token.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
