# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protobuf/auth.proto\x12\ttodo_auth\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"-\n\x0bUserProfile\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"5\n\x0fUserCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"H\n\x14UserRegistrationForm\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t2\xcf\x01\n\x0b\x41uthService\x12>\n\x10\x41uthenticateUser\x12\x10.todo_auth.Token\x1a\x16.todo_auth.UserProfile\"\x00\x12\x43\n\x0cRegisterUser\x12\x1f.todo_auth.UserRegistrationForm\x1a\x10.todo_auth.Token\"\x00\x12;\n\tLoginUser\x12\x1a.todo_auth.UserCredentials\x1a\x10.todo_auth.Token\"\x00\x62\x06proto3')



_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_USERPROFILE = DESCRIPTOR.message_types_by_name['UserProfile']
_USERCREDENTIALS = DESCRIPTOR.message_types_by_name['UserCredentials']
_USERREGISTRATIONFORM = DESCRIPTOR.message_types_by_name['UserRegistrationForm']
Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'protobuf.auth_pb2'
  # @@protoc_insertion_point(class_scope:todo_auth.Token)
  })
_sym_db.RegisterMessage(Token)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILE,
  '__module__' : 'protobuf.auth_pb2'
  # @@protoc_insertion_point(class_scope:todo_auth.UserProfile)
  })
_sym_db.RegisterMessage(UserProfile)

UserCredentials = _reflection.GeneratedProtocolMessageType('UserCredentials', (_message.Message,), {
  'DESCRIPTOR' : _USERCREDENTIALS,
  '__module__' : 'protobuf.auth_pb2'
  # @@protoc_insertion_point(class_scope:todo_auth.UserCredentials)
  })
_sym_db.RegisterMessage(UserCredentials)

UserRegistrationForm = _reflection.GeneratedProtocolMessageType('UserRegistrationForm', (_message.Message,), {
  'DESCRIPTOR' : _USERREGISTRATIONFORM,
  '__module__' : 'protobuf.auth_pb2'
  # @@protoc_insertion_point(class_scope:todo_auth.UserRegistrationForm)
  })
_sym_db.RegisterMessage(UserRegistrationForm)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKEN._serialized_start=34
  _TOKEN._serialized_end=56
  _USERPROFILE._serialized_start=58
  _USERPROFILE._serialized_end=103
  _USERCREDENTIALS._serialized_start=105
  _USERCREDENTIALS._serialized_end=158
  _USERREGISTRATIONFORM._serialized_start=160
  _USERREGISTRATIONFORM._serialized_end=232
  _AUTHSERVICE._serialized_start=235
  _AUTHSERVICE._serialized_end=442
# @@protoc_insertion_point(module_scope)
