# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/todo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/todo.proto',
  package='todo_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13protobuf/todo.proto\x12\x0ctodo_service\"3\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"*\n\x07NewTodo\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\".\n\x0eTodoIdentifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\x1f\n\x0bTodoCreator\x12\x10\n\x08username\x18\x01 \x01(\t\".\n\tTodosList\x12!\n\x05todos\x18\x01 \x03(\x0b\x32\x12.todo_service.Todo\"\x11\n\x0fSuccessResponse2\xcc\x02\n\x0bTodoService\x12@\n\x08GetTodos\x12\x19.todo_service.TodoCreator\x1a\x17.todo_service.TodosList\"\x00\x12\x39\n\nCreateTodo\x12\x15.todo_service.NewTodo\x1a\x12.todo_service.Todo\"\x00\x12=\n\x07GetTodo\x12\x1c.todo_service.TodoIdentifier\x1a\x12.todo_service.Todo\"\x00\x12\x34\n\x08\x45\x64itTodo\x12\x12.todo_service.Todo\x1a\x12.todo_service.Todo\"\x00\x12K\n\nDeleteTodo\x12\x1c.todo_service.TodoIdentifier\x1a\x1d.todo_service.SuccessResponse\"\x00\x62\x06proto3'
)




_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='todo_service.Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo_service.Todo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='todo_service.Todo.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='todo_service.Todo.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=88,
)


_NEWTODO = _descriptor.Descriptor(
  name='NewTodo',
  full_name='todo_service.NewTodo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='todo_service.NewTodo.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='todo_service.NewTodo.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=132,
)


_TODOIDENTIFIER = _descriptor.Descriptor(
  name='TodoIdentifier',
  full_name='todo_service.TodoIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todo_service.TodoIdentifier.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='todo_service.TodoIdentifier.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=180,
)


_TODOCREATOR = _descriptor.Descriptor(
  name='TodoCreator',
  full_name='todo_service.TodoCreator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='todo_service.TodoCreator.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=213,
)


_TODOSLIST = _descriptor.Descriptor(
  name='TodosList',
  full_name='todo_service.TodosList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='todos', full_name='todo_service.TodosList.todos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=261,
)


_SUCCESSRESPONSE = _descriptor.Descriptor(
  name='SuccessResponse',
  full_name='todo_service.SuccessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=280,
)

_TODOSLIST.fields_by_name['todos'].message_type = _TODO
DESCRIPTOR.message_types_by_name['Todo'] = _TODO
DESCRIPTOR.message_types_by_name['NewTodo'] = _NEWTODO
DESCRIPTOR.message_types_by_name['TodoIdentifier'] = _TODOIDENTIFIER
DESCRIPTOR.message_types_by_name['TodoCreator'] = _TODOCREATOR
DESCRIPTOR.message_types_by_name['TodosList'] = _TODOSLIST
DESCRIPTOR.message_types_by_name['SuccessResponse'] = _SUCCESSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), {
  'DESCRIPTOR' : _TODO,
  '__module__' : 'protobuf.todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_service.Todo)
  })
_sym_db.RegisterMessage(Todo)

NewTodo = _reflection.GeneratedProtocolMessageType('NewTodo', (_message.Message,), {
  'DESCRIPTOR' : _NEWTODO,
  '__module__' : 'protobuf.todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_service.NewTodo)
  })
_sym_db.RegisterMessage(NewTodo)

TodoIdentifier = _reflection.GeneratedProtocolMessageType('TodoIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _TODOIDENTIFIER,
  '__module__' : 'protobuf.todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_service.TodoIdentifier)
  })
_sym_db.RegisterMessage(TodoIdentifier)

TodoCreator = _reflection.GeneratedProtocolMessageType('TodoCreator', (_message.Message,), {
  'DESCRIPTOR' : _TODOCREATOR,
  '__module__' : 'protobuf.todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_service.TodoCreator)
  })
_sym_db.RegisterMessage(TodoCreator)

TodosList = _reflection.GeneratedProtocolMessageType('TodosList', (_message.Message,), {
  'DESCRIPTOR' : _TODOSLIST,
  '__module__' : 'protobuf.todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_service.TodosList)
  })
_sym_db.RegisterMessage(TodosList)

SuccessResponse = _reflection.GeneratedProtocolMessageType('SuccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSRESPONSE,
  '__module__' : 'protobuf.todo_pb2'
  # @@protoc_insertion_point(class_scope:todo_service.SuccessResponse)
  })
_sym_db.RegisterMessage(SuccessResponse)



_TODOSERVICE = _descriptor.ServiceDescriptor(
  name='TodoService',
  full_name='todo_service.TodoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=283,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTodos',
    full_name='todo_service.TodoService.GetTodos',
    index=0,
    containing_service=None,
    input_type=_TODOCREATOR,
    output_type=_TODOSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTodo',
    full_name='todo_service.TodoService.CreateTodo',
    index=1,
    containing_service=None,
    input_type=_NEWTODO,
    output_type=_TODO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodo',
    full_name='todo_service.TodoService.GetTodo',
    index=2,
    containing_service=None,
    input_type=_TODOIDENTIFIER,
    output_type=_TODO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditTodo',
    full_name='todo_service.TodoService.EditTodo',
    index=3,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTodo',
    full_name='todo_service.TodoService.DeleteTodo',
    index=4,
    containing_service=None,
    input_type=_TODOIDENTIFIER,
    output_type=_SUCCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOSERVICE)

DESCRIPTOR.services_by_name['TodoService'] = _TODOSERVICE

# @@protoc_insertion_point(module_scope)
