apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: todo-app
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-server
          image: todo-app-auth-service:v1
          ports:
            - containerPort: 3005
          env:
            - name: DB_HOST
              value: auth-database-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-database-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: todo-app
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 3000
      targetPort: 3005
